### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by LeoBdt** [tim03we/SlashSkin#1]
Add geometry skin and perms for each skin?

**Comment by tim03we** [comment]
Why the geometric? 
Permissions can be inserted.

**Comment by LeoBdt** [comment]
Because with geometry skin you can have more kind of skin

**Comment by LeoBdt** [comment]
Not only human skin

**Comment by tim03we** [comment]
Let's see.

**Comment by LeoBdt** [comment]
You can use this api? https://github.com/Blugin/GeometryAPI-PMM

Here's an example of what custom geometry skin is. [
![49876_5b54edc30d758](https://user-images.githubusercontent.com/11062780/58714024-217a4280-83c4-11e9-8453-8d00744badb2.png)
](url)

**Comment by tim03we** [comment]
We'll see if I'll include geometric skins or not.

**Comment by LeoBdt** [comment]
Thanks.
